### ISSUE TITLE
Paths in Ant files

### ISSUE THREAD

**Issue by alainbernard** [opcoach/genModelAddon#28]
Strange paths in the generated Ant file.
Example:
`		<emf.Ecore2Java genModel="model/platform:/resource/myPluginId/model/airports.genmodel" 
			model="model/platform:/resource/myPluginId/model/airports.ecore" `

**Comment by opcoach** [comment]
Only on windows.. the name of the model was extracted using File.separator which is '\' on windows.. but the URI contains only '/'... Fixed with a unit test
