### ISSUE TITLE
Missing scrollbar

### ISSUE THREAD

**Issue by st20085** [opcoach/genModelAddon#36]
Hello Olivier

There is a display bug in the file list box: missing a scrollbar when there are many files files to edit: I do not see the 2 buttons to select or not the files (see screenshot)
![missing scrollbar](https://cloud.githubusercontent.com/assets/6695434/13783195/a4c8866a-eaca-11e5-9241-3e7d0590c01d.png)
also the path displays the two '/' and '\' characters

**Comment by opcoach** [comment]
Fixed.
