### ISSUE TITLE
Composition references does not work when pattern is not M{0}

### ISSUE THREAD

**Issue by alainbernard** [opcoach/genModelAddon#38]
When we use somthing else than M{0} in interface name pattern (for example G{0}), composition references are not well generated. For example, for my class Vehicle which is contained in my RentalAgency, I should have in GRentalAgency interface:
    EList<Vehicle> getRentals();
Instead, I have:
    EList<GVehicle> getRentals();

**Comment by opcoach** [comment]
Hi Alain, 

Don't understand your issue... ? 

Did you mean that you should have :  
     EList<Vehicule> getRentals() 
and you got 
     EList<GVehicule> getRentals

Right ?

**Comment by alainbernard** [comment]
Hi Olivier,
Generic type arguments have disappeared in my message... 
I meant that I have:
`EList<GVehicle> getRentals()` instead of `EList<Vehicle> getRentals()`

**Comment by opcoach** [comment]
Right, the M name was fixed in the name transformation instead of getting the value in genmodel !

**Comment by st20085** [comment]
Hi Olivier

I have yet the problem with version 1.6.0 
In interface MFanNoiseProject I have 
```
MWorkflow getWorkflow(); instead of Workflow getWorkflow();
EList<MThermodynamicCondition> getThermodynamicConditions(); instead of EList<ThermodynamicCondition> getThermodynamicConditions(); 
```

Here is my very very simplified plugin (I use 2 Ecore/GenModel maybe source of the problem)
[bug.on.genmodeladdon.zip](https://github.com/opcoach/genModelAddon/files/214909/bug.on.genmodeladdon.zip)

**Comment by opcoach** [comment]
I will not reopen this bug because it is due to issue #12 which is not yet fixed... It is because 2 genmodel are imbricated...

**Comment by opcoach** [comment]
I added tests and the fannoise project to start investigation :)

See commit : 20373c38d047fa280127dfa94ddccc6ee7261f04

**Comment by opcoach** [comment]
Cyril, 

I fixed the bug.. launch the build in the build/com.opcoach.genmodeladdon.parent with : 

mvn clean install

And install the zip in generated in : 

build/com.opcoach.genmodeladdon.repository/target/com.opcoach.genmodeladdon.repository-1.6.0-SNAPSHOT.zip
