### ISSUE TITLE
src-gen code not generated at all

### ISSUE THREAD

**Issue by MatthieuPERIN** [opcoach/genModelAddon#78]
Hello, 

I have run with success the generation run on the ecore sample model you provide, but when I try to use it on my genmodel, the /src code is well generated but the /src-gen source folder remains empty (the EMF generation progress bar goes on very quickly).

I have run successfully "generate Model" from genmodel standard generation but I wish to use your tool (because of the name swaping in generated methods that helps a lot extending the generated code), and I have validate the EMF generation option for sure :).

I have try to get ride of my previous hand-written code (in /src) with no better results.
No error, no console output triggered to help me understand what is happening :(

I join you the UML model, the genmodel & associated ecore model if you can provide me some help !

Have nice day (and thx for the tool !)

[railtopomodel.ecore.txt](https://github.com/opcoach/genModelAddon/files/3319952/railtopomodel.ecore.txt)
[railtopomodel.genmodel.txt](https://github.com/opcoach/genModelAddon/files/3319953/railtopomodel.genmodel.txt)
[railtopomodel.uml.txt](https://github.com/opcoach/genModelAddon/files/3319954/railtopomodel.uml.txt)

**Comment by opcoach** [comment]
Hi Matthieu, 

Thank you to use genModelAddon. 

Do you use the latest version of genModelAddon (2.1.0) ?  

 I provide in the dialog a way to initialize the generation with the correct values. 




If the first part, I guess you have ’src’ for the gen source directory. If this is so, you should click on edit values and then on set relevant values. 

The src-gen parameter for the genmodel is a parameter initialized in the Model Properties / Model Source Directory (you can get it in the properties when you click on the top level node or your genmodel).

Let me know if you found it and if it works for you. 

If not, I will try with your models. 

Olivier


  <http://www.opcoach.com/>
Olivier Prouvost

Formation et Expertise Eclipse

 	
 olivier.prouvost@opcoach.com
 http://www.opcoach.com <http://www.opcoach.com/>
 +33(0)6 28 07 65 64
 OPCoach_Eclipse <https://twitter.com/OPCoach_Eclipse>
 Profil linkedin
 <https://fr.linkedin.com/in/olivierprouvost>	 	  <https://eclipse.org/membership/showMember.php?member_id=987>

**Comment by MatthieuPERIN** [comment]
Hi Olivier, thanks for the answer, to reply to your remarks :
* My GenModelAddon is the 2.1.0 from your repo (I am on a 2018-12 eclipse)
* The dialog open correctly (both of them actually) and I have configured it correctly (as It work perfectly for the sample Ecore provided in your com.opcoach.genmodeladdon.sample plugin)

The src is generated correctly but nothing append for the associated src-gen ... whereas it is working perfectly with a direct genModel "generate model code"....

I have tried to run it in a clean new plugin without any better results :/

Hope you can help me on this ;) (and thanks again for support !)

**Comment by opcoach** [comment]
Ok Matthieu, 

The generate dev source is used only to generate the code for the developper part. The dialog is able also to launch the generated EMF code in src-gen, if you click in the box, but if you use the ‘generate model code’ from EMF it will populate also the src-gen directory… 

The good practice if you change your Ecore and genmodel is : 
To always regenerate the EMF source code
To regenerate the src code only if you have added some EClasses in your Ecore file.
To remove manually the code in src for the deleted class in your Ecore

May be I should explain it in the documentation. 

Hope this help. If not feel free to ask me again. 

By the way, where are you from ? 

Olivier



  <http://www.opcoach.com/>
Olivier Prouvost

Formation et Expertise Eclipse

 	
 olivier.prouvost@opcoach.com
 http://www.opcoach.com <http://www.opcoach.com/>
 +33(0)6 28 07 65 64
 OPCoach_Eclipse <https://twitter.com/OPCoach_Eclipse>
 Profil linkedin
 <https://fr.linkedin.com/in/olivierprouvost>	 	  <https://eclipse.org/membership/showMember.php?member_id=987>

**Comment by MatthieuPERIN** [comment]
Thanks for the hints 👍 

The issue is that when I generate directly the src-gen folder is filled (this is OK) but when I run your plugin with the generate EMF code option ticked, nothing happen... strange to me.

More strange, the dev source generate a factory for my top level EPackage in /src whereas the generate Model from genmodel does not generate such factory (leading to a inconsistent alignement between src and src-gen)

Finally, a question about model configuration (not directly link to my issue) if I may:
How do you manage to have typing using the final /src names {0} in your methods and not the M{0} names (leading to a generated code that is not viable without the src part but more easy to extend !) ?

**Comment by opcoach** [comment]
Hi Matthieu, 

I have reproduced the bug and I will check it asap. There must be an error during the call to the EMF generation, while when this is  done by the EMF menu, it is ok.  I will probably add a unit test for that. 

For the factories I will check also. 

May be you should not have so many packages if you change the DSL, you should use several included Ecore models (with load resource). Are you sure that location and topology are in the same ‘DSL’ ? You should read this article about it : 

https://eclipsesource.com/blogs/2013/03/19/emf-dos-and-donts-5/ <https://eclipsesource.com/blogs/2013/03/19/emf-dos-and-donts-5/>

For the question about the names I have overridden the GenModelFactory with my own factory that computes the expected names without changing the JET template and to adapt automatically to the current EMF generator version. 

You can see that in the genmodeladdon.core plugin. 

I will try to fix the bug asap ! 

Thanks for reporting. 

Olivier


  <http://www.opcoach.com/>
Olivier Prouvost

Formation et Expertise Eclipse

 	
 olivier.prouvost@opcoach.com
 http://www.opcoach.com <http://www.opcoach.com/>
 +33(0)6 28 07 65 64
 OPCoach_Eclipse <https://twitter.com/OPCoach_Eclipse>
 Profil linkedin
 <https://fr.linkedin.com/in/olivierprouvost>	 	  <https://eclipse.org/membership/showMember.php?member_id=987>

**Comment by MatthieuPERIN** [comment]
Thanks (a lot) for your efforts.

I have no hand on the railtopomodel Model as it is a Standard, thus enforced by a given extrenal (UML) meta-model ! But I will definitively have a look at the link provided for the additional model I have to build uppon :)

Can you point me the entry point for the GenModelFatcory overload in the plugin, I have try to find it without any success :(

**Comment by opcoach** [comment]
Hi Matthieu, 
I had a look tonight on your project, and I found something. 

In the src model I generate useless classes for the factories and packages. It occurs when a package contains other packages without any  classes... -> I must remove the factory and package generation when there are no classes in the package. In addition, the extensions generated for factory_override and generated package should not be generated. 

For the moment, the workaround for you is to remove the failed factory and package classes generated in src (RailtopomodelFactory, RailtopomodelPackage, RailtopomodelFactoryImpl.java), and the associated generated packages and factory_override) and also the 2 extensions generated as described in the picture. 

I will fix and add a test asap. 

![fix78_toomanyfilesgenerated](https://user-images.githubusercontent.com/1716878/60628184-96400280-9df0-11e9-9f05-b71d01e72aea.png)

**Comment by opcoach** [comment]
The bug is in /com.opcoach.genmodeladdon.core/src/com/opcoach/genmodeladdon/core/GenerateDevStructure.xtend.  line 143 and 144. It must not be called if there are only packages in the current package... 

I have no time to fix it tonight and to add the test, but that should be done quickly.

**Comment by opcoach** [comment]
By the way Matthieu, for the first problems : EMF code not generated, if you have a look in the error log you get an error... even if you use directly the 'Generate Model Code'.. I did not investigate but may be there is a problem with the imported types or with some configuration in your genmodel.

**Comment by MatthieuPERIN** [comment]
Thanks for the pointer for the EMF generation and thanks a lot for the bug correction, It is very pleasant to see open source project to react that quickly.

Great Job !
