### ISSUE TITLE
Generated getInstance() method not compliant with Java6

### ISSUE THREAD

**Issue by alainbernard** [opcoach/genModelAddon#8]
The generated getInstance() method in the overriden factory is not compliant with Java6 execution environment. It generates compilation errors as shown by the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/10706697/6231921/00760244-b6c9-11e4-81ab-29a87ac30e08.png)

**Comment by opcoach** [comment]
Fixed with cda3de9c34cadb3afd8ccf6efb2cf4038aa98513
I kept the eINSTANCE standard usage instead of getInstance.
