### ISSUE TITLE
 la classe *Package.java n'a pas obtenu son suffixe

### ISSUE THREAD

**Issue by JeanGarf** [opcoach/genModelAddon#80]
Salut Olivier,

J'ai utilisé genModelAddon cet après-midi.

ANOMALIE
Ca a marché impec, sauf pour la classe *Package.java 

Toutes les autres classes ont bien été créées et nommée *Custom.java comme je l'avais demandé.

CONTOURNEMENT
Renommer manuellement la classe *Package.java en *PackageCustom.java

CORRECTION ATTENDUE
Prendre en coompte le suffixe, y compris pour la classe *Package<suffix>.java

**Comment by opcoach** [comment]
The problem is in the computation of the name for the Package interface in the src generation. Not sure that this class is still used and I guess it has been fixed by Issue #74 but not yet delivered officially.

**Comment by JeanGarf** [comment]
Yes it seems to be the same problem than #74.

How may I install the fix ?

**Comment by opcoach** [comment]
you can clone the genmodeladdon project and build it with : 

mvn clean install

Then you can use the build/com.opcoach.genmodeladdon.repository/target/com.opcoach.genmodeladdon.repository-2.2.0-SNAPSHOT.zip as a zipped update site and install it in your current Eclipse instance

I will provide it in a few time (I would like to fix the last bugs before...).

**Comment by JeanGarf** [comment]
OK,

Thanks

**Comment by JeanGarf** [comment]
Bonjour Olivier,

1) J'ai  buildé avec le mvn clean install, ça s'est bien passé, puis j'ai installé la v2.2.0_SNAPSHOT dans mon IDE Eclipse.

J'ai vérifié que les plugin installés sont les suivants :
	OPCOACH	Core	2.2.0.201908130947	com.opcoach.genmodeladdon.core
	Eclipse Modeling Project	GenModel Editor based on EMFForms	1.21.0.20190603-0953	org.eclipse.emfforms.editor.genmodel
	OPCOACH	Genmodeladdon	2.2.0.201908130947	com.opcoach.genmodeladdon.ui

2) Les nommages suivants sont correctement pris en compte cette fois-ci quand j'exécute GenModelAddon

src-gen interface **GenI{0}**
src-gen classe **Gen{0}**

src interface **I{0}**
src classe **{0}**

et on a bien **src** qui **dépend** de **src-gen** et **pas l'inverse**.

3) Mais il y a **2 problèmes** maintenant, 

a. il **manque** les **Factory** et **Packages** dans **src-gen** (en revanche, elles sont correctement générées dans src).
b. Et surtout, ça **bloque Eclipse** et je suis obligé de le **killer**.

Je suis à peu près sûr que ça vient de GenModelAddon, car j'ai fini par **le désinstaller** et là, la génération du **src-gen** s'est déroulée **correctement**.

Et je n'ai plus d'erreurs de compilation.

Est-ce que ce sont des bugs connus ?

**Comment by opcoach** [comment]
I tried again with different naming pattern : Dev{0}Custom or Gen{0}ToBeCustomized and I got no problem with the generation. I used the new 2.2.0 version. 
Please reopen if you still find a bug ...
