### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [opcoach/genModelAddon#83]
Hello genModelAddon team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the genModelAddon project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by opcoach** [comment]
Hi Tamas, 

Thank you for this issue. Here is the piece of html : 

<tr>
	<td><a href="http://opcoach.github.io/genModelAddon/">genModelAddon</a></td>
	<td>This project is used to separate properly the EMF generated code and your developed code.</td>
	<td>Eclipse Public License 1.0</td>
	<td>Code generator</td>
	<td>Olivier Prouvost (OPCoach) olivier@opcoach.com</td>
</tr>

**Comment by miklossy** [comment]
Than you Olivier!

**Comment by miklossy** [comment]
The `genModelAddon` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
